In [109]:
import numpy as np
from scipy import stats

# ДЗ №8 Гладышев В.В.

## Задание №1

Объясняемая переменная `y` зависит от двух категориальных факторов `A` и `B`, причём фактор `A` имеет 3 уровня, а фактор `B` - 4 уровня. Результаты наблюдений приведены в таблице:

```
y = [[2.68, 3.29, 2.88, 4.45],
     [4.12, 4.96, 5.09, 5.22],
     [5.52, 4.50, 5.42, 5.29]]
```

С помощью двухфакторного дисперсионного анализа проверьте влияние каждого из факторов на переменную `y`.

In [110]:
y = np.array([[2.68, 3.29, 2.88, 4.45],
     [4.12, 4.96, 5.09, 5.22],
     [5.52, 4.50, 5.42, 5.29]])

y

array([[2.68, 3.29, 2.88, 4.45],
       [4.12, 4.96, 5.09, 5.22],
       [5.52, 4.5 , 5.42, 5.29]])

In [111]:
k = y.shape[0]
m = y.shape[1]
n = k * m
mean_t = y.mean()
mean_i = y.mean(axis=1)
mean_j = y.mean(axis=0)

k, m, n, mean_t, mean_i, mean_j

(3,
 4,
 12,
 4.451666666666666,
 array([3.325 , 4.8475, 5.1825]),
 array([4.10666667, 4.25      , 4.46333333, 4.98666667]))

In [112]:
s_a = k * np.sum((mean_i-mean_t)**2)
s_b = m * np.sum((mean_j-mean_t)**2)
s_w = np.sum((y - mean_i.reshape(mean_i.shape[0], 1) - mean_j + mean_t)**2)

s_a, s_b, s_w

(5.880537499999999, 1.7842222222222253, 1.9298833333333332)

In [113]:
d_a = s_a/(m - 1)
d_b = s_b/(k - 1)
d_w = s_w/((m - 1)*(k - 1))

d_a, d_b, d_w

(1.9601791666666664, 0.8921111111111126, 0.3216472222222222)

In [114]:
F_a = d_a/d_w
F_b = d_b/d_w

F_a, F_b

(6.094189631497586, 2.7735700776385497)

In [115]:
alpha = 0.05
F_a_crit = stats.f.ppf(1 - alpha, m - 1, n - m)
F_b_crit = stats.f.ppf(1 - alpha, k - 1, n - k)

F_a_crit, F_b_crit

(4.06618055135116, 4.25649472909375)

При уровне значимости $\alpha = 0.05$

$F_A > F_{crit, \: A}$ Фактор А оказывает статистически значимое влияние

$F_B < F_{crit, \: B}$ Фактор В не оказывает статистически значимого влияния

## Задание №2

С помощью критерия Стьюдента для двух независимых выборок проверьте гипотезу о равенстве среднего роста футболистов и хоккеистов, основываясь на результатах измерений:

```
football_players = [173, 175, 180, 178, 177, 185, 183, 182]
hockey_players = [177, 179, 180, 188, 177, 172, 171, 184, 180]
```

In [118]:
football_players = [173, 175, 180, 178, 177, 185, 183, 182]
hockey_players = [177, 179, 180, 188, 177, 172, 171, 184, 180]

In [123]:
n_f = len(football_players)
n_h = len(hockey_players)
m_f = np.mean(football_players)
m_h = np.mean(hockey_players)
v_f = np.var(football_players, ddof=1)
v_h = np.var(hockey_players, ddof=1)

T = (m_f - m_h)/np.sqrt(v_f/n_f + v_h/n_h)
m_f, m_h, T

(179.125, 178.66666666666666, 0.19928601397363732)

In [122]:
alpha = 0.05

t = stats.t.ppf(1 - alpha / 2, df=n_f+n_h-2)
t

2.131449545559323

$-t < T < t$ Гипотезу не отклоняем

## Задание №3

Прикрепите ссылку на курсовой проект на `github`

https://github.com/VitalyGladyshev/Math_Ess/blob/master/%D0%93%D0%BB%D0%B0%D0%B4%D1%8B%D1%88%D0%B5%D0%B2%20Forests%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82.ipynb