In [1]:
import numpy as np

# ДЗ №8 ГладышевВВ
## Тема 6 СЛАУ

## Заготовка для ДЗ Занять место :)
### Пока решены задания 1, 2

###  Задание 1

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [3]:
Ainv = np.linalg.inv(A)
print(Ainv)
print("det =", np.linalg.det(A))
print(Ainv@B)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det = 59.999999999999986
[-9.2         0.9         6.46666667]


###  Задание 2

In [4]:
A2 = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B2 = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A2, B2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [5]:
np.dot(A2, [1.13919353, -0.90498444, -0.9009803])

array([ 0.23020495,  7.03751835, 11.83650984,  6.78328856, 15.21805317])

In [6]:
np.dot(A2, [1.13919353, -0.90498444, -0.9009803]) - B2

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])

###  Задание 3

###  Задание 4

###  Задание 5

###  Задание 6