In [17]:
import numpy as np

# ДЗ №7 ГладышевВВ
## Тема 5 Введение в линейную алгебру

###  Задание 1.1

In [18]:
a1 = np.array([[0], [1], [2]], float)
print(a1)

[[0.]
 [1.]
 [2.]]


In [19]:
b1 = np.array([3, 4, 5], float)
print(b1)

[3. 4. 5.]


In [20]:
print(a1 * 2)

[[0.]
 [2.]
 [4.]]


In [21]:
np.dot(b1, a1)

array([14.])

###  Задание 2

In [22]:
d = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.det(d)

59.999999999999986

In [23]:
1*(0*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 0*7)

60

###  Задание 3

In [24]:
d = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.matrix_rank(d, 0.0001)

3

In [25]:
A_d = np.array([[-48, 6, 32], [6, -12, 6], [12, 6, -8]])
print(A_d.transpose())

[[-48   6  12]
 [  6 -12   6]
 [ 32   6  -8]]


In [26]:
print(A_d.transpose()/np.linalg.det(d))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [27]:
print(np.linalg.inv(d))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


###  Задание 4

In [28]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)

s = np.inner(a, b)
print(s)

42.0


###  Задание 5

In [29]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print(v)
print(np.inner(v, c))

[35. -7. -2.]
228.5
