In [2]:
import numpy as np

# Тема 5 Введение в линейную алгебру

## Матрицы и векторы

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 12]], float)
print(a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 0. -1. 12.]]


In [4]:
print(a[2, 1])

8.0


In [5]:
print(a.shape)

(4, 3)


### Операции с матрицами

In [7]:
b = a * 2
print(b)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]
 [ 0. -2. 24.]]


In [11]:
# Матрицу нельзя складывать с константой. Хотя, в Python работает
c = a + 1
print(c)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]
 [ 1.  0. 13.]]


In [9]:
d = np.add(c, b)
print(d)

[[ 4.  7. 10.]
 [13. 16. 19.]
 [22. 25. 28.]
 [ 1. -2. 37.]]


In [12]:
d = c + b
print(d)

[[ 4.  7. 10.]
 [13. 16. 19.]
 [22. 25. 28.]
 [ 1. -2. 37.]]


In [15]:
d = np.subtract(b, c)
print(d)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [-1. -2. 11.]]


In [13]:
print(b - c)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [-1. -2. 11.]]


### Транспонирование матрицы

In [17]:
f =  d.transpose()
print(d)
print("")
print(f)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [-1. -2. 11.]]

[[ 0.  3.  6. -1.]
 [ 1.  4.  7. -2.]
 [ 2.  5.  8. 11.]]


### Умножение матриц

In [19]:
i, j = 0, 0
d[i, 0] * f[0, j] + d[i, 1] * f[1, j] + d[i, 2] * f[2, j]

5.0

In [30]:
g = np.dot(f, d)
print(g)
f.shape, d.shape

[[ 46.  56.  52.]
 [ 56.  70.  56.]
 [ 52.  56. 214.]]


((3, 4), (4, 3))

### Единичная и нулевая матрицы

In [31]:
e = np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
np.dot(g, e)

array([[ 46.,  56.,  52.],
       [ 56.,  70.,  56.],
       [ 52.,  56., 214.]])

### Обратная матрица

In [33]:
p = np.linalg.inv(g)
print(p)

[[ 1.11904762 -0.85714286 -0.04761905]
 [-0.85714286  0.67460317  0.03174603]
 [-0.04761905  0.03174603  0.00793651]]


In [34]:
np.dot(g, p)

array([[ 1.00000000e+00, -6.27276009e-15, -3.74700271e-16],
       [-5.71764858e-15,  1.00000000e+00, -2.77555756e-17],
       [ 7.35522754e-16, -2.85882429e-15,  1.00000000e+00]])

In [35]:
np.dot(p, g)

array([[ 1.00000000e+00,  6.16173779e-15,  6.03683770e-15],
       [-1.15740750e-14,  1.00000000e+00, -9.64506253e-15],
       [-5.96744876e-16, -4.71844785e-16,  1.00000000e+00]])

### Свойства сложения и умножения матриц
#### (k * l) * A = k * (l * A)
#### k * (A + B) = k * A + k * B
#### (k + l) * A = k * A + l * A
#### (A * B) * C = A * (B * C)
#### (A + B) * C = A * C + B * C
#### A * (B + C) = A * B +  A * C

### ДЗ 1.1

In [37]:
a1 = np.array([[0], [1], [2]], float)
print(a1)

[[0.]
 [1.]
 [2.]]


In [39]:
b1 = np.array([3, 4, 5], float)
print(b1)

[3. 4. 5.]


In [40]:
print(a1 * 2)

[[0.]
 [2.]
 [4.]]


In [42]:
np.dot(b1, a1)

array([14.])

## Определитель матрицы
#### det A

In [3]:
a = np.array([[1, 2], [3, 4]])
print(a)
a[0, 0] * a[1, 1] - a[0, 1] * a[1, 0]

[[1 2]
 [3 4]]


-2

In [4]:
np.linalg.det(a)

-2.0000000000000004

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(b)

-9.51619735392994e-16

#### det A

In [6]:
1*(5*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 5*7)

0

### Свойства определителей

#### 1 Определитель не меняется при транспонировании.

#### 2 При перестановке двух соседних строк (столбцов) определитель меняет знак.

#### 3 Определитель с двумя одинаковыми строками (столбцами) равен нулю.

#### 4 Общий множитель строки (столбца) можно выносить за знак определителя.

#### 5 Если все элементы некоторой строки (столбца) равны нулю, то определитель равен нулю.

#### 6 Если элементы двух строк (или двух столбцов) пропорциональны, то определитель равен нулю.

#### 7 Если к элементам некоторой строки (столбца) прибавить соответствующие элементы другой строки (столбца), предварительно умножив их на одно и то же отличное от нуля число, то определитель не изменится.

In [7]:
np.linalg.det(b)

-9.51619735392994e-16

### ДЗ 2

## Вычисление обратной матрицы. Ранг матрицы.

### Обратная матрица

#### A^-1 = A'^T/det A

### Ранг матрицы

#### Если из матрицы (необязательно квадратной) вычеркнуть несколько столбцов и строк, так, чтобы в результате осталась матрица МхМ, то определитель оставшейся матрицы называют минором порядка М исходной матрицы.

#### или: Минором порядка М матрицы А будем называть определитель М-го порядка с элементами, лежащими на пересечении любых М строк и М столбцов матрицы А.

#### Рангом матрицы называют наибольший из порядков отличных от нуля её миноров.

In [8]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(a)
np.linalg.det(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


0.0

### Линейная независимость столбцов или строк

In [9]:
np.linalg.matrix_rank(a, 0.0001)

2

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(b)
np.linalg.matrix_rank(b, 0.0001)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

### ДЗ 3